image: node:6.9.4

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - npm install
            - npm test
      - step:
          name: Build
          script:
            - npm run build
