image: node:6.9.4

pipelines:
  branches:
    master:
      - step:
          name: Prepare
          script:
            - npm install
      - step:
          name: Test
          script:
            - npm test
